CC=gcc

all:
	$(CC) -g \
		-Wall \
        -O2 \
		cluster.c \
		clusterGraph.c \
		clusterGraphMoveNodes.c \
		clusterReadTree.c \
		clusterStructsGraphAndTree.c \
		clusterStructsStacks.c \
		clusterStructMinValues.c \
		-o cluster

egcc:
	egcc -g \
		-Wall \
        -O2 \
		cluster.c \
		clusterGraph.c \
		clusterGraphMoveNodes.c \
		clusterReadTree.c \
		clusterStructsGraphAndTree.c \
		clusterStructsStacks.c \
		clusterStructMinValues.c \
		-o cluster
