CC=gcc

all:
	$(CC) -g \
		-Wall\
		-O2\
		scoreReads.c \
		scoreReadsCheckCigarEntry.c \
		scoreReadsScoringWrappers.c \
		scoreReadsRefCheckCigarEntry.c \
		scoreReadsConversion.c \
		scoreReadsFileIO.c \
		scoreReadsGlobalVar.c \
		scoreReadsSamFileFunctions.c \
		scoreReadsStructers.c \
		-o scoreReads

egcc:
	egcc -g \
		-Wall\
		-O2\
		scoreReads.c \
		scoreReadsCheckCigarEntry.c \
		scoreReadsScoringWrappers.c \
		scoreReadsRefCheckCigarEntry.c \
		scoreReadsConversion.c \
		scoreReadsFileIO.c \
		scoreReadsGlobalVar.c \
		scoreReadsSamFileFunctions.c \
		scoreReadsStructers.c \
		-o scoreReads
